### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by ilemhadri** [jjfeng/spinn#2]
Is there any plan to provide an R version of the software?

That would be super helpful!

**Comment by jjfeng** [comment]
Hi,

I do not plan to release an R version of this software. However, you might be interested in this instead: https://github.com/jjfeng/easier_net_R

This is the latest update to SPINN. We are now advocating a slightly different structure, and have found it to be easier to fit and more accurate. (If you want the latest version of this manuscript, please email me. The one on arxiv is a bit old.)

Jean

**Comment by ilemhadri** [comment]
Sounds good! I just emailed j*****@gmail.com
